### ISSUE TITLE
Import another quickjson or existing json endpoint

### ISSUE THREAD

**Issue by rochacbruno** [heltonalves99/quickjson#1]
I would use this service to generate random posts for quokka cms populate with sample data feature, this will create a lot of posts in CMS for testings and showcase.

But I would ask for a new feature

Based in official example

``` json
{
    "title": ["text", 40],
    "summary": ["text", 100],
    "tags": ["words", 10],
    "authors": ["from", "http://quickjson.com/generate/10c110fbba64?count=3"]
}
```

And then, http://quickjson.com/generate/10c110fbba64?count=3 generate a list of authors to fill there

``` json
[
{
"name": "Yazmin Greenholt",
"email": "mayert.jaye@mcclure.info"
},
{
"name": "Loran Kling",
"email": "mueller.justice@vonrueden.biz"
},
{
"name": "Madora Conn",
"email": "dubuque.sharee@hotmail.com"
}
]
```

**Comment by heltonalves99** [comment]
Feature created, now accepts import another quickjson or existing json endpoint! o/

**Comment by heltonalves99** [comment]
Feature created, now accepts import another quickjson or existing json endpoint! o/
